language: node_js
addons:
  sauce_connect: true
env:
  global:
    - secure: iDyPv5kIVjlUlzx9uZLR6M07seLI0FbRSY9WE0gVLdxYIK6tj4VD9RzxDU9Ou6QeEf0zThHh40p3p1tEK6fLV39Izb3LNvooFyYZuvzrWJBWoVDPQ4CnSb9NQyR7ZkZLgCGAbDPe4aWAYQkAD1YJgnB0XyuDY7owFl9fMN3GDXHQ+ERDAibv9re6OG4RT1GukNKlIUpkNDmv68ImWRKEbHhBdObm5t9ywm4mMjyjHiF1AfKuYPtI+jg84Nw7MPECqduExQUcbe6Jlk5zq3VSaHVYSi1VZrvHXMzjgZbX44ngiIhvxxGLbXxaX3xHIcIKKn5ELnIVTR9Q1Zf1++GGABz3Ul+sXrj8TEWqE32oyMQ0ufGn1FbvP+7R07wnJQe8q17OxaDcGVSxWxIocYECGe/0EaJRcCIlcw7DJtHEiTUvTtZTMEsI5KMUnnbD47+hNo8p4CbzHlyZLDz/e49fztYoEXfraTS2/jFT2gmjBJOzfuwRwOBorNmaLRzv3TgvKwowaPJal9tmqrukaXmgvyG300465uwt2D7jpOizG31xDM/ZbZfXkm8R1lR1tccXVr87xYoMolKWXysDpngG5U/Ce0azPT7BEg9mwHRFDgATfMWlDFNf728c5upRu8yI7zjMcuF9nSQZmivGsTeg5Kxg2F1PCaxW1DFX2R0dr6E=
    - secure: dfYBGtVWl6oHuNYD0132K+jQNF26Ws/8iD5wXgbHg9KXcjxZi9nCGbXYl3SyHGUdWoLJzqZPq8ONDiNfwiq48wf88m+TjjwJMSEtRbqfs1YEj9dxWQq80K3iNkXhi//5SsotocG23NPKlcth2CPfPZWoCt9N4/gcqO+vn2YyP4z46yR4uAZRtiTwMBKUVVih3QcndYkhnNeLJTlFW0SfMGFn/jH7ViVyHpXOwhMNCGUo3OzCUSSwRlgG+qtS2/ZbyPdlSHIkvOO1bstGO04g8TUaepl1+w/T3EZ0LaOdnluycDCdXgTOn1AuOkKKKNdgm6xTi9N2rM6Ma2wq2F+9EzGrKvJJ+nIXk0vGnBL1CUW6IUz9hDqNugCmOK3YDOpfcRvsiWsVUGRdTgZ2eClMkjqGusKnlWqTanwkRpHFRZh8SEf/lXXS2aTOLOzx9EIyvFeZQMeDulx5jcEhUSMoaX0WZen00PA3C+lTwgWvH2RM8dAkCh0RSFSMscyQwEQ6bUppfZLjDuBhr7dz+muTAhPQrxKzthxqTSFgzv+Jq6G4z753a2zem7pXLel/j2N7qnVZUQUkcvBPc85atvnJkSSYpp0GxwQBUNjGA/DafvLZ6Kha8wywRJzA2b2N73NTYn/a4cxGrBcjiEtptFpfq9C5j93fql2XTUi06i39ewM=
before_script:
  - pwd
  - python -m SimpleHTTPServer &
  - sleep 2
  - npm install -g grunt-cli && npm install -g bower
  - cd test/selenium && npm install

node_js:
    - "stable"
